### ISSUE TITLE
kind requires a config file

### ISSUE THREAD

**Issue by chuckha** [chuckha/capi-dev#1]
This needs a config file for kind to mount the socket into the kind node

**Comment by chuckha** [comment]
probably something like

```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
```
